== ISO/TC 211 Geolexica Database

NOTE: The documentation below is intended for database operators.
Please contact the ISO/TC 211 TMG for change proposals on terms and concepts
in the MLGT database.

This repository contains the latest snapshot of ISO/TC 211 Geolexica glossary in YAML format.

This repository is used as the database used by both
https://github.com/geolexica/isotc211.geolexica.org[ISO/TC 211 Geolexica website]
and the Glossarist desktop app.

This database is represented online by https://geolexica.org/.

NOTE: The YAML data in this repository is not yet an authoritative data source.
Currently, data stored in this structure is imported from the latest published
ISO/TC 211 Multi-Lingual Glossary of Terms spreadsheets.
In the future, all data will be managed through the Glossarist desktop application.


=== Authoritative spreadsheet data import toolchain

While the Geolexica Glossarist application is being developed,
TC 211 continues to maintain the glossary in spreadsheets
which remain to be authoritative data sources.

During this period, facilities to import those spreadsheets into Geolexica data
are included in this repository.

MLGT management will transition to the Glossarist workflow once the
terminology repository can be migrated to Glossarist.

==== Setup

Generation of YAML files require Ruby and the `yq` binary to be installed.

==== Usage

To rewrite the YAML glossary with data migrated from those sources, run:

[source,sh]
----
make all
----

After a successful YAML glossary build, a new snapshot of the database
is committed in this repository.
This will trigger isotc211.geolexica.org to be rebuilt.


==== Troubleshooting... and more

Behind the scenes, the Makefile uses `tc211-termbase` gem that converts spreadsheet files to YAML.

The intermediate file `tc211-termbase.xlsx` is used as the
direct data source for all concepts and terms in Geolexica.

The source spreadsheet files are provided in a separate private repository:
https://github.com/ISO-TC211/mlgt-data[mlgt-data].

The particular spreadsheet file used for generation is set in the Makefile.

This spreadsheet file is necessary for running the `tc211-termbase-xlsx2yaml` command.

See https://github.com/iso-tc211/tc211-termbase[tc211-termbase] repository
for details of the migration.


== Data structure

There are two types of entries in the database:

. Concepts

. Terms (Designations in ISO 10241-1), which represent concepts in actual languages


=== Concepts

Every concept is recognized by a unique ID (the "`term id`"), and contains terms
in different languages.

Here's an example from the `_concepts/` directory (which has to be built).

[source,yaml]
----
eng:
  id: 2
  term: abbreviation
  alt: preferred
  definition: designation formed by omitting words or letters from a longer form and
    designating the same concept
  language_code: eng
  notes: []
  examples: []
  entry_status: valid
  authoritative_source: ISO 1087-1:2000, 3.4.9
  lineage_source: ISO/TS 19104:2008
  lineage_source_similarity: 1
  date_accepted: 2008-11-15 00:00:00.000000000 +08:00
  review_date: 2013-01-29 00:00:00.000000000 +08:00
  review_status: final
  review_decision: accepted
  review_decision_date: 2016-10-01 00:00:00.000000000 +08:00
  review_decision_event: Publication of ISO 19104:2016
  review_decision_notes: Authoritative reference changed from ISO 1087-1:2000 to ISO
    1087-1:2000, 3.4.9. Lineage source added as ISO/TS 19104:2008
  release: '2'
ara:
  ...
----


=== Designation / Term

A designation / term contains multiple attributes, such as:

[source,yaml]
----
id: 2
term: abbreviation
alt: preferred
definition: designation formed by omitting words or letters from a longer form and
  designating the same concept
language_code: eng
notes: []
examples: []
entry_status: valid
authoritative_source: ISO 1087-1:2000, 3.4.9
...
----

